### ISSUE TITLE
climdexGrid() function returns monthly outputs instead of yearly when crossing season is specified

### ISSUE THREAD

**Issue by fmsangi** [SantanderMetGroup/climate4R.climdex#7]
I am trying to calculate climate change indices for a specific crossing season (October to April) from 1981 to 2020 but I get results as months instead of the season year. For the given period 1981 to 2020, I expected the output to have 39 seasons layers but it returns 273 monthly layers. Is there a way for me to specify that a year is defined after 212 days(days between October and April no leap)?

Please find my code below and attached data

#Calculating the indices
ds1<-"/Volumes/Untitled 2/Daily kk/Daily2_pr19812020.nc"

ppt.eobs <- loadGridData(dataset = ds1,
                            var = "ppt",
                            years = 1982:2020,
                            season = c(10,11,12,1,2,3,4))

PRCPTOT.indices=climdexGrid('PRCPTOT',pr =ppt.eobs,input.arg.list = list(base.range=c(1982,2020),northern.hemisphere=FALSE),cal = "365_day")
[Daily2_pr19812020.nc.zip](https://github.com/SantanderMetGroup/climate4R.climdex/files/8629262/Daily2_pr19812020.nc.zip)

**Comment by miturbide** [comment]
Hi fmsangi
The climate4R.climdex package is a wrapper of the PCICt package, which by definition works with complete annual series. However, you can use the following approach instead:

library(transformeR)
library(loadeR)

ds1<-"/home/maialen/Downloads/Daily2_pr19812020.nc"

ppt.eobs <- loadGridData(dataset = ds1,
                         var = "ppt",
                         years = 1982:2020,
                         season = c(10,11,12,1,2,3,4))

aux.fun <- function(x){
  sum(x[x >= 1])
}

prcptot <- aggregateGrid(ppt.eobs, aggr.y = list(FUN = aux.fun))

**Comment by fmsangi** [comment]
Hi miturbide

Thank you very much for the clarification and suggested approach it solved my problem
